[package]
name = "encrust"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
block-modes = "0.9"
rand = "0.8"
hex = "0.4"
clap = { version = "4.5.4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }  # for async support
