[package]
name = "encrust"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20poly1305 = "0.10.1"
aes = "0.8.4"
aes-gcm = "0.10.3"
rand = "0.8"
hex = "0.4"
clap = { version = "4.5.4", features = ["derive"] }